stages:
- template: "../stages_template.yml"
  parameters:
    clientEnvironments:
      ProjectName: "TEST
      Platforms:
        - Platform: "AWS"
          AccountSequenceNumber: 1
          DCCRegionalHub: "AME"
          Chargecode: "LPEGAWS"
          CmsCode: "DT-CCMS"
          CountryCode: "DTTL"
          Function: "CON"
          DataQualifier: "PUB_PUB"
          CustomerName: "Test_AWS"
          MemberFirm: "US"
          Networking:
            - region: "ap-south-1"
              netAddressMask: 27
              subAddressMasks: "[27]"
              description: "VPC with mask 27"
              updateCidrBlock: false
              addSecondaryCidrBlock: true
              secSubAddressMasks: "[27]"
              
            - region: "ap-south-1"
              netAddressMask: 27
              subAddressMasks: "[27]"
              description: "VPC with mask 27"
              updateCidrBlock: false
              addSecondaryCidrBlock: true
              secSubAddressMasks: "[28,28]"
          AccessProvisioning:
            - users:
                - "a-dcc@dell.com"
              permissionGroup: "PowerUser"
